import Footer from '@/components/layouts/Footer';
import Header from '@/components/layouts/Header';
import '@/styles/globals.css';
import '@/styles/index.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko">
			<body
				style={{
					display: 'grid',
					gridTemplateRows: 'auto 1fr auto',
					minHeight: '100vh',
				}}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
