import Footer from '@/components/layouts/Footer';
import Header from '@/components/layouts/Header';
import '@/styles/globals.css';
import '@/styles/index.css';
import type { Metadata } from 'next';
import { bodyStyle } from './layout.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko">
			<body className={bodyStyle}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
